### ISSUE TITLE
TargetsdkVersion > 23 and ANIMATABLE_XWALK_VIEW  cause a Build Crash

### ISSUE THREAD

**Issue by pisze-programy** [fantasy525/react-native-crosswalk-webview-plus#10]
I'm using Webview as Textureview (`(XwalkPreferences.setValue(XWalkPreferences.ANIMATABLE_XWALK_VIEW, true);` flag) but I'm not able to build project with `targetSdkVersion > 23`. 

`Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable
        at org.xwalk.core.ReflectConstructor.newInstance(ReflectConstructor.java:54)
        at org.xwalk.core.XWalkView.reflectionInit(XWalkView.java:2082)
        at org.xwalk.core.XWalkView.<init>(XWalkView.java:261)
` 

(without this flag, Webview is SurfaceView - it's hard to create bitmap from it)

I need this flag to grab screenshot of Webview. Is there other way to grab screenshot and build with target > 23 ?

**Comment by pisze-programy** [comment]
Ok, so I used Surfaceview (`ANIMATABLE_XWALK_VIEW=false`) and create new API method called `captureBitmapAsync`. For all of you, check my fork:

https://github.com/Krbz/react-native-crosswalk-webview-plus/commit/f5a9b28f82b7da957547fea55a2cb7d137d42dd1
